live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
decorations = "buttonless"
dynamic_padding = false

[window.padding]
x = 8
y = 8

[font]
size = 13.0
offset = { x = -1, y = 0 }

[font.bold]
family = "SFMono Nerd Font"
style = "Medium"

[font.bold_italic]
family = "SFMono Nerd Font"
style = "Medium Italic"

[font.italic]
family = "SFMono Nerd Font"
style = "Regular Italic"

[font.normal]
family = "SFMono Nerd Font"
style = "Regular"

# Colors (Gruvbox Material Hard Dark)

# Default colors
[colors.primary]
background = '#1d2021'
foreground = '#d4be98'

# Normal colors
[colors.normal]
black   = '#32302f'
red     = '#ea6962'
green   = '#a9b665'
yellow  = '#d8a657'
blue    = '#7daea3'
magenta = '#d3869b'
cyan    = '#89b482'
white   = '#d4be98'

# Bright colors (same as normal colors)
[colors.bright]
black   = '#32302f'
red     = '#ea6962'
green   = '#a9b665'
yellow  = '#d8a657'
blue    = '#7daea3'
magenta = '#d3869b'
cyan    = '#89b482'
white   = '#d4be98'
