live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
decorations = "buttonless"
dynamic_padding = false

[window.padding]
x = 8
y = 8

[font]
size = 13.0
offset = { x = -1, y = 0 }

[font.bold]
family = "SFMono Nerd Font"
style = "Medium"

[font.bold_italic]
family = "SFMono Nerd Font"
style = "Medium Italic"

[font.italic]
family = "SFMono Nerd Font"
style = "Regular Italic"

[font.normal]
family = "SFMono Nerd Font"
style = "Regular"

# Colors (Tokyo Night Storm variant)
# Source https//github.com/zatchheems/tokyo-night-alacritty-theme

# Default colors
[colors.primary]
background = '#24283b'
foreground = '#a9b1d6'

# Normal colors
[colors.normal]
black   = '#32344a'
red     = '#f7768e'
green   = '#9ece6a'
yellow  = '#e0af68'
blue    = '#7aa2f7'
magenta = '#ad8ee6'
cyan    = '#449dab'
white   = '#9699a8'

# Bright colors
[colors.bright]
black   = '#444b6a'
red     = '#ff7a93'
green   = '#b9f27c'
yellow  = '#ff9e64'
blue    = '#7da6ff'
magenta = '#bb9af7'
cyan    = '#0db9d7'
white   = '#acb0d0'
